apiVersion: argoproj.io/v1alpha1  
kind: Application  
metadata:  
  name: common-resources  
  namespace: argocd  
spec:  
  project: common-resources  
  source:  
    repoURL: https://github.com/staslebedenko/dev-infrastructure.git  # Adjust to your actual repository URL  
    targetRevision: HEAD  
    path: apps/common/base                # Path to your common manifests  
  destination:  
    server: https://kubernetes.default.svc  
    namespace: default               # For namespace resources, use "default" namespace destination  
  syncPolicy:  
    automated:  
      prune: false                   # Be careful with pruning namespaces!  
      selfHeal: true  