apiVersion: v1  
kind: ConfigMap  
metadata:  
  name: argocd-rbac-cm  
  namespace: argocd  
data:  
  policy.csv: |  
    g, devbcn, role:devbcn-demo-admin  
  policy.default: role:readonly  
  scopes: '[groups]'  
  policy.roles: |  
    p, role:devbcn-demo-admin, applications, *, devbcn-demo/*, allow  
    p, role:devbcn-demo-admin, projects, get, devbcn-demo, allow  