apiVersion: argoproj.io/v1alpha1  
kind: Application  
metadata:  
  name: common-resources  
  namespace: argocd  
spec:  
  project: common-resources  
  source:  
    repoURL: https://github.com/staslebedenko/dev-infrastructure.git  
    targetRevision: HEAD  
    path: apps/common/base  
  destination:  
    server: https://kubernetes.default.svc  
    namespace: default  
  syncPolicy:  
    automated:  
      prune: false  
      selfHeal: true  